#! /usr/bin/env bash
if [[ `whoami` == 'root' ]]; then
  echo "please do not run as root"
  exit 1
fi

sudo apt-get install python-pip python-dev python-virtualenv
# Oops ... this is not mentioned on the install docks
# https://www.tensorflow.org/install/install_linux#InstallingVirtualenv
which virtualenv || sudo easy_install virtualenv
test -e bin || virtualenv --system-site-packages .
source bin/activate

